import Head from "next/head";
import CompanyProfile from "../Components/CompanyProfile/CompanyProfile";
import HeroSection from "../Components/HeroSection/HeroSection";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Next Js Webiste</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <CompanyProfile />
    </div>
  );
}
